apiVersion: v1
kind: Pod
metadata:
  name: log-test
  namespace: default
spec:
  serviceAccountName: log-collector
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]
