apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-read-role
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
